name: graphql_fetch
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: draco <email@example.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: any
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0

